# Generated by Django 5.0.2 on 2024-03-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencySupportResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('helpline_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('additional_information', models.TextField(blank=True)),
            ],
        ),
    ]
