# Generated by Django 5.0.1 on 2024-04-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_alter_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="location", new_name="address",
        ),
        migrations.RenameField(
            model_name="profile", old_name="profileimg", new_name="photo",
        ),
        migrations.AddField(
            model_name="profile",
            name="First_Name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="Last_Name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="mobile_number",
            field=models.CharField(default="1234567890", max_length=15),
        ),
    ]
