# Generated by Django 5.0.1 on 2024-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_rename_location_profile_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="address", new_name="location",
        ),
        migrations.RenameField(
            model_name="profile", old_name="photo", new_name="profileimg",
        ),
        migrations.RemoveField(model_name="profile", name="First_Name",),
        migrations.RemoveField(model_name="profile", name="Last_Name",),
        migrations.RemoveField(model_name="profile", name="mobile_number",),
        migrations.AlterField(
            model_name="profile", name="id_user", field=models.IntegerField(),
        ),
    ]
