# Generated by Django 5.0.1 on 2024-02-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login_Authentication", "0010_alter_userloginauth_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userloginauth",
            name="otp_key",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
