# Generated by Django 5.0.1 on 2024-02-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login_Authentication", "0011_userloginauth_otp_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="userloginauth",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
