# Generated by Django 5.0.1 on 2024-03-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Login_Authentication", "0012_userloginauth_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="userloginauth", name="image",),
        migrations.RemoveField(model_name="userloginauth", name="otp_key",),
    ]
