# Generated by Django 5.0.1 on 2024-03-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=500)),
                ("event_date", models.CharField(max_length=25)),
                ("event_details", models.TextField()),
            ],
        ),
    ]
