# Generated by Django 5.0.1 on 2024-02-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Login_Authentication", "0002_customattribute"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomAttribute",),
    ]
