# Generated by Django 5.0.1 on 2024-02-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Login_Authentication", "0005_remove_userloginauth_user_reg_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userloginauth", name="email_address",),
    ]
