# Generated by Django 5.0.1 on 2024-02-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login_Authentication", "0007_alter_userloginauth_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userloginauth",
            name="email_address",
            field=models.EmailField(
                default=None, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userloginauth",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
