# Generated by Django 5.0.1 on 2024-02-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login_Authentication", "0009_alter_userloginauth_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloginauth",
            name="phone_number",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
