# Generated by Django 5.0.1 on 2024-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_author_alter_article_author_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="author", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="book", name="author", field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(name="Author",),
    ]
