# Generated by Django 5.0.1 on 2024-04-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_alter_article_author_alter_book_author_delete_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="podcast", name="image",),
    ]
