# Generated by Django 5.0.1 on 2024-02-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login_Authentication", "0008_userloginauth_email_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloginauth",
            name="phone_number",
            field=models.CharField(default=None, max_length=13, unique=True),
        ),
    ]
