# Generated by Django 5.0.1 on 2024-04-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="feedback", name="updated_at",),
    ]
