# Generated by Django 5.0.1 on 2024-02-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Support_Group", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Support_Group", new_name="SupportGroup",),
    ]
