# Generated by Django 5.0.1 on 2024-03-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Find_Doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="category",
            field=models.CharField(
                choices=[
                    ("Psychologist", "Psychologist"),
                    ("Psychiatrist", "Psychiatrist"),
                ],
                default="Psychologist",
                max_length=20,
            ),
        ),
    ]
